import type { Metadata } from 'next'
import './globals.css'
import { authOptions } from './api/auth/[...nextauth]/route'
import { getServerSession } from 'next-auth/next'
import { SessionProvider } from './components/SessionProvider'
import Login from './components/Login'

export const metadata: Metadata = {
  title: 'NEXT AUTH',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body>
        <SessionProvider session={session}>
          {!session ? <Login /> : (
            <div>
              {children}
            </div>
          )}
        </SessionProvider>
      </body>
    </html>
  )
}
